# Generated by Django 4.2 on 2026-01-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='The Monday of the report week', verbose_name='Week Start Date')),
                ('week_end_date', models.DateField(help_text='The Sunday of the report week', verbose_name='Week End Date')),
                ('week_number', models.PositiveIntegerField(help_text='ISO week number of the year', verbose_name='Week Number')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('total_grns_received', models.PositiveIntegerField(default=0, help_text='Total number of Goods Received Notes created during the week', verbose_name='Total GRNs Received')),
                ('total_grn_line_items', models.PositiveIntegerField(default=0, help_text='Total number of line items across all GRNs', verbose_name='Total GRN Line Items')),
                ('total_net_value_received', models.DecimalField(decimal_places=2, default=0, help_text='Sum of net values from all GRN line items', max_digits=18, verbose_name='Total Net Value Received')),
                ('total_gross_value_received', models.DecimalField(decimal_places=2, default=0, help_text='Sum of gross values (including tax) from all GRN line items', max_digits=18, verbose_name='Total Gross Value Received')),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total tax amount (gross - net)', max_digits=18, verbose_name='Total Tax Amount')),
                ('total_invoices_created', models.PositiveIntegerField(default=0, help_text='Total number of invoices created during the week', verbose_name='Total Invoices Created')),
                ('total_invoices_approved', models.PositiveIntegerField(default=0, help_text='Total number of invoices fully approved during the week', verbose_name='Total Invoices Approved')),
                ('total_approved_payment_value', models.DecimalField(decimal_places=2, default=0, help_text='Total gross value of approved invoices (vendor payments processed)', max_digits=18, verbose_name='Total Approved Payment Value')),
                ('total_invoices_rejected', models.PositiveIntegerField(default=0, help_text='Total number of invoices rejected during the week', verbose_name='Total Invoices Rejected')),
                ('total_invoices_pending', models.PositiveIntegerField(default=0, help_text='Total number of invoices still pending approval at week end', verbose_name='Total Invoices Pending')),
                ('unique_vendors_received', models.PositiveIntegerField(default=0, help_text='Number of unique vendors with goods received', verbose_name='Unique Vendors (Received)')),
                ('unique_vendors_paid', models.PositiveIntegerField(default=0, help_text='Number of unique vendors with approved payments', verbose_name='Unique Vendors (Paid)')),
                ('unique_stores_received', models.PositiveIntegerField(default=0, help_text='Number of unique stores that received goods', verbose_name='Unique Stores')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional report data or breakdowns')),
            ],
            options={
                'verbose_name': 'Weekly Report',
                'verbose_name_plural': 'Weekly Reports',
                'ordering': ['-year', '-week_number'],
            },
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['year', 'week_number'], name='reports_ser_year_ce094f_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['week_start_date'], name='reports_ser_week_st_65c448_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('year', 'week_number')},
        ),
    ]
