# Generated by Django 4.2 on 2025-10-13 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egrn_service', '0021_alter_conversion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=32, unique=True)),
                ('delivery_id', models.CharField(max_length=50, unique=True)),
                ('source_location_id', models.CharField(help_text='Warehouse/Location ID from SAP ByD', max_length=50)),
                ('source_location_name', models.CharField(blank=True, help_text='Warehouse/Location name', max_length=100)),
                ('delivery_date', models.DateField()),
                ('delivery_status_code', models.CharField(choices=[('1', 'Open'), ('2', 'In Process'), ('3', 'Completed'), ('4', 'Cancelled')], default='1', max_length=1)),
                ('delivery_type_code', models.CharField(blank=True, help_text='SAP ByD delivery type code', max_length=10)),
                ('sales_order_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('destination_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_deliveries', to='egrn_service.store')),
            ],
            options={
                'verbose_name': 'Inbound Delivery',
                'verbose_name_plural': 'Inbound Deliveries',
            },
        ),
        migrations.CreateModel(
            name='InboundDeliveryLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=32)),
                ('product_id', models.CharField(max_length=32)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity_expected', models.DecimalField(decimal_places=3, max_digits=15)),
                ('quantity_received', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('unit_of_measurement', models.CharField(max_length=32)),
                ('metadata', models.JSONField(default=dict)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='transfer_service.inbounddelivery')),
            ],
            options={
                'verbose_name': 'Inbound Delivery Line Item',
                'verbose_name_plural': 'Inbound Delivery Line Items',
            },
        ),
        migrations.CreateModel(
            name='TransferReceiptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.IntegerField(unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('posted_to_icg', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destination_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_received', to='egrn_service.store')),
                ('inbound_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='transfer_service.inbounddelivery')),
            ],
            options={
                'verbose_name': 'Transfer Receipt Note',
                'verbose_name_plural': 'Transfer Receipt Notes',
            },
        ),
        migrations.CreateModel(
            name='TransferReceiptLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=3, max_digits=15)),
                ('metadata', models.JSONField(default=dict)),
                ('inbound_delivery_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_receipt_items', to='transfer_service.inbounddeliverylineitem')),
                ('transfer_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='transfer_service.transferreceiptnote')),
            ],
            options={
                'verbose_name': 'Transfer Receipt Line Item',
                'verbose_name_plural': 'Transfer Receipt Line Items',
            },
        ),
        migrations.CreateModel(
            name='StoreAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Store Manager'), ('assistant', 'Assistant Manager'), ('clerk', 'Store Clerk'), ('viewer', 'Viewer Only')], max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_users', to='egrn_service.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Authorization',
                'verbose_name_plural': 'Store Authorizations',
                'unique_together': {('user', 'store')},
            },
        ),
    ]
