# Generated by Django 4.2 on 2025-10-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferreceiptnote',
            name='destination_store',
        ),
    ]
