# Generated by Django 4.2 on 2025-08-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbounddelivery',
            name='source_store',
        ),
        migrations.AddField(
            model_name='inbounddelivery',
            name='delivery_type_code',
            field=models.CharField(blank=True, help_text='SAP ByD delivery type code', max_length=10),
        ),
        migrations.AddField(
            model_name='inbounddelivery',
            name='source_location_id',
            field=models.CharField(default='4100007-5', help_text='Warehouse/Location ID from SAP ByD', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inbounddelivery',
            name='source_location_name',
            field=models.CharField(blank=True, help_text='Warehouse/Location name', max_length=100),
        ),
    ]
