# Generated by Django 4.2 on 2025-10-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_service', '0002_remove_transferreceiptnote_destination_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferreceiptnote',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
