# Generated by Django 4.2.26 on 2026-02-05 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer_service', '0003_transferreceiptnote_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbounddeliverylineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Unit price from SAP ByD', max_digits=15),
        ),
        migrations.AddField(
            model_name='transferreceiptnote',
            name='approval_status',
            field=models.CharField(choices=[('pending_receipt', 'Pending Receipt'), ('receipt_submitted', 'Receipt Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted')], default='pending_receipt', help_text='Current approval status in the two-stage workflow', max_length=25),
        ),
        migrations.AddField(
            model_name='transferreceiptnote',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When sending store approved the receipt', null=True),
        ),
        migrations.AddField(
            model_name='transferreceiptnote',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User from sending store who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfer_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferreceiptnote',
            name='rejection_count',
            field=models.IntegerField(default=0, help_text='Number of times receipt has been rejected'),
        ),
        migrations.AddField(
            model_name='transferreceiptnote',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection by sending store', null=True),
        ),
        migrations.AddField(
            model_name='transferreceiptnote',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When receiving store submitted the receipt', null=True),
        ),
        migrations.AddField(
            model_name='transferreceiptnote',
            name='synced_to_sap',
            field=models.BooleanField(default=False, help_text='Whether receipt has been synced to SAP ByD'),
        ),
        migrations.CreateModel(
            name='MaterialPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(db_index=True, max_length=50)),
                ('material_name', models.CharField(blank=True, max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('site_id', models.CharField(blank=True, help_text='Location/warehouse this price applies to', max_length=50, null=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Source or reason for this pricing')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Pricing',
                'verbose_name_plural': 'Material Pricing',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['material_id', '-effective_date'], name='transfer_se_materia_d8a0f7_idx'), models.Index(fields=['material_id', 'site_id', '-effective_date'], name='transfer_se_materia_a7d803_idx')],
            },
        ),
    ]
