# Generated by Django 4.2 on 2026-02-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_service', '0003_transferreceiptnote_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferreceiptnote',
            name='posted_to_icg',
        ),
    ]
