# Generated by Django 4.2 on 2026-03-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_service', '0004_inbounddeliverylineitem_unit_price_and_more'),
        ('transfer_service', '0004_remove_posted_to_icg'),
    ]

    operations = [
    ]
