# Generated by Django 4.2.26 on 2026-05-19 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer_service', '0005_merge_20260313_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceLocationAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_location_id', models.CharField(help_text='Warehouse/Location ID from SAP ByD', max_length=50)),
                ('source_location_name', models.CharField(blank=True, help_text='Auto-populated from SAP on save', max_length=100)),
                ('role', models.CharField(choices=[('approver', 'Approver'), ('viewer', 'Viewer Only')], default='approver', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_location_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Source Location Authorization',
                'verbose_name_plural': 'Source Location Authorizations',
                'unique_together': {('user', 'source_location_id')},
            },
        ),
    ]
