# Generated by Django 4.2.26 on 2026-05-19 12:55

from django.db import migrations


def backfill_scd_authorizations(apps, schema_editor):
    """
    Existing SCD_Team members had implicit access to every warehouse (the old
    ``get_user_authorized_source_locations`` returned ``None`` for them, meaning
    "all"). Now that access is explicit per-warehouse, grant each existing
    SCD_Team user an 'approver' row for every distinct source_location_id that
    already exists in InboundDelivery, so day-one nobody loses access.

    Admins can curate from there. Future SCD users start with zero access by
    default and must be assigned explicitly.
    """
    Group = apps.get_model("auth", "Group")
    InboundDelivery = apps.get_model("transfer_service", "InboundDelivery")
    SourceLocationAuthorization = apps.get_model("transfer_service", "SourceLocationAuthorization")

    try:
        scd_group = Group.objects.get(name="SCD_Team")
    except Group.DoesNotExist:
        return

    scd_users = list(scd_group.user_set.all())
    if not scd_users:
        return

    # Build a {location_id: name} map from the most-recent delivery per warehouse.
    location_names = {}
    for delivery in InboundDelivery.objects.order_by("-created_date").only(
        "source_location_id", "source_location_name"
    ):
        loc_id = delivery.source_location_id
        if loc_id and loc_id not in location_names:
            location_names[loc_id] = delivery.source_location_name or ""

    if not location_names:
        return

    to_create = []
    for user in scd_users:
        for loc_id, loc_name in location_names.items():
            to_create.append(
                SourceLocationAuthorization(
                    user=user,
                    source_location_id=loc_id,
                    source_location_name=loc_name,
                    role="approver",
                )
            )

    SourceLocationAuthorization.objects.bulk_create(to_create, ignore_conflicts=True)


def reverse_backfill(apps, schema_editor):
    """
    Reverse cleanly: delete every authorization row that the forward migration
    could have created (any SCD_Team user x any warehouse currently in
    InboundDelivery). Non-SCD assignments added manually by admins after the
    migration ran are preserved.
    """
    Group = apps.get_model("auth", "Group")
    InboundDelivery = apps.get_model("transfer_service", "InboundDelivery")
    SourceLocationAuthorization = apps.get_model("transfer_service", "SourceLocationAuthorization")

    try:
        scd_group = Group.objects.get(name="SCD_Team")
    except Group.DoesNotExist:
        return

    scd_user_ids = list(scd_group.user_set.values_list("id", flat=True))
    location_ids = list(
        InboundDelivery.objects.values_list("source_location_id", flat=True).distinct()
    )
    if not scd_user_ids or not location_ids:
        return

    SourceLocationAuthorization.objects.filter(
        user_id__in=scd_user_ids,
        source_location_id__in=location_ids,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_service', '0006_sourcelocationauthorization'),
    ]

    operations = [
        migrations.RunPython(backfill_scd_authorizations, reverse_backfill),
    ]
