# Generated by Django 4.2 on 2024-08-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_service', '0002_keystore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='signature',
            field=models.TextField(),
        ),
    ]
