# Generated by Django 4.2 on 2024-08-06 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval_service', '0003_alter_signature_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='approval_service.signature'),
        ),
    ]
