# Generated by Django 4.2 on 2025-02-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval_service', '0004_signature_predecessor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signature',
            options={'verbose_name': '5.1 Signature', 'verbose_name_plural': '5.1 Signatures'},
        ),
    ]
