"""
Django settings for vimp project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.getenv('DEBUG', default="0")))

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

CORS_ORIGIN_ALLOW_ALL = True

# CSRF_TRUSTED_ORIGINS = ['localhost:3000', '20.101.63.100', "*.wajesmarthrms.website"]

AUTH_USER_MODEL = 'core_service.CustomUser'

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = os.getenv("SMTP_HOST")
EMAIL_PORT = os.getenv("SMTP_PORT")
EMAIL_HOST_USER = os.getenv("EMAIL_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD")

USE_L10N = False
USE_THOUSAND_SEPARATOR = True

# Application definition
INSTALLED_APPS = [
	'unfold',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	
	'rest_framework',
	'rest_framework_simplejwt',
	'corsheaders',
	'jsoneditor',
	'django_q',
	'cachalot',

	'core_service',
	'egrn_service',
	'invoice_service',
	'approval_service',
	'byd_service',
	'app_settings',
]

JSON_EDITOR_JS = 'https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/8.6.4/jsoneditor.js'
JSON_EDITOR_CSS = 'https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/8.6.4/jsoneditor.css'

UNFOLD = {
	"SITE_ICON": lambda request: "https://foodconceptsplc.com/wp-content/uploads/2019/10/FoodConcepts_Favicon.png",
	"SITE_LOGO": lambda request: "https://foodconceptsplc.com/wp-content/uploads/2019/10/FoodConcepts_Logo-1.png",
	"SITE_FAVICONS": [
		{
			"rel": "icon",
			"sizes": "32x32",
			"type": "image/svg+xml",
			"href": lambda request: "https://foodconceptsplc.com/wp-content/uploads/2019/10/FoodConcepts_Favicon.png",
		},
	],
	"COLORS": {
		"primary": {
			"50": "235 242 250",
			"100": "199 217 240",
			"200": "158 186 225",
			"300": "117 154 210",
			"400": "41 87 164",
			"500": "76 123 195",
			"600": "41 87 164",
			"700": "33 70 131",
			"800": "25 52 98",
			"900": "16 35 66",
			"950": "8 17 33",
		},
	},
}

Q_CLUSTER = {
	'name': 'vimp_workers',
	'orm': 'default',
	'timeout': 300,  # 5 minutes timeout
	'retry': 360,   # 6 minutes retry (must be larger than timeout)
	'ack_failures': True,  # Acknowledge failures to prevent retries on permanent failures
	'max_attempts': 3,
	'save_limit': 1000,  # Increase save limit for task results
	'queue_limit': 500,  # Limit queue size to prevent memory issues
	'catch_up': False,  # Don't catch up on missed schedules
	'guard_cycle': 5,  # Check cluster health every 5 seconds
	'log_level': 'INFO', # Log level for the cluster
}

REST_FRAMEWORK = {
	'DEFAULT_AUTHENTICATION_CLASSES': (
		'rest_framework_simplejwt.authentication.JWTAuthentication',
		'django_auth_adfs.rest_framework.AdfsAccessTokenAuthentication',
		'rest_framework.authentication.SessionAuthentication',
		'rest_framework.authentication.BasicAuthentication',
	),
	'DEFAULT_PERMISSION_CLASSES': (
		'rest_framework.permissions.IsAuthenticated',
	),
	'DEFAULT_PAGINATION_CLASS': 'overrides.rest_framework.CustomPagination',
	'PAGE_SIZE': 15,
	'DEFAULT_RENDERER_CLASSES': [
		'rest_framework.renderers.JSONRenderer',
	] if not DEBUG else [
		'rest_framework.renderers.JSONRenderer',
		'rest_framework.renderers.BrowsableAPIRenderer',
	],
	'DEFAULT_THROTTLE_CLASSES': [
		'rest_framework.throttling.AnonRateThrottle',
		'rest_framework.throttling.UserRateThrottle'
	],
	'DEFAULT_THROTTLE_RATES': {
		'anon': '100/hour',
		'user': '1000/hour'
	}
}

AUTHENTICATION_BACKENDS = (
	'django_auth_adfs.backend.AdfsAccessTokenBackend',
	'django.contrib.auth.backends.ModelBackend',
)

AUTH_ADFS = {
	'AUDIENCE': os.getenv('CLIENT_ID'),
	'CLIENT_ID': os.getenv('CLIENT_ID'),
	'CLIENT_SECRET': os.getenv('CLIENT_SECRET'),
	'CLAIM_MAPPING': {'first_name': 'given_name',
					  'last_name': 'family_name',
					  'email': 'upn'},
	'GROUPS_CLAIM': 'roles',
	'MIRROR_GROUPS': True,
	'USERNAME_CLAIM': 'upn',
	'TENANT_ID': os.getenv('TENANT_ID'),
	'RELYING_PARTY_ID': os.getenv('CLIENT_ID'),
	'LOGIN_EXEMPT_URLS': [
		'^api',
		'^admin'
	],
}

# Logging Configuration
LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'formatters': {
		'verbose': {
			'format': '%(levelname)s %(asctime)s %(name)s %(message)s'
		},
	},
	'handlers': {
		'console': {
			'class': 'logging.StreamHandler',
			'formatter': 'verbose',
			'level': 'DEBUG',
		},
	},
	'loggers': {
		'django_auth_adfs': {
			'handlers': ['console'],
			'level': 'WARNING',
		},
	},
}

if not DEBUG:
	# Production performance settings
	ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')
	
	# Security settings for production
	SECURE_BROWSER_XSS_FILTER = True
	SECURE_CONTENT_TYPE_NOSNIFF = True
	X_FRAME_OPTIONS = 'DENY'
	
	# Session optimization
	SESSION_COOKIE_AGE = 3600  # 1 hour
	SESSION_SAVE_EVERY_REQUEST = False
	
	# File upload settings
	FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
	DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

	# Logging optimization for production
	LOGGING['handlers']['file'] = {
		'level': 'WARNING',
		'class': 'logging.handlers.RotatingFileHandler',
		'filename': 'logs/vimp.log',
		'maxBytes': 1024*1024*10,  # 10MB
		'backupCount': 5,
		'formatter': 'verbose'
	}
	LOGGING['loggers']['django']['handlers'] = ['file']
	LOGGING['loggers']['vimp'] = {
		'handlers': ['file'],
		'level': 'WARNING',
		'propagate': False,
	}


SIMPLE_JWT = {
	'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
	'ACCESS_TOKEN_LIFETIME': timedelta(hours=5),
	'ROTATE_REFRESH_TOKENS': True,
	'BLACKLIST_AFTER_ROTATION': True,
	'UPDATE_LAST_LOGIN': True,
	'ALGORITHM': 'HS256',
	'SIGNING_KEY': SECRET_KEY,
	'AUTH_HEADER_TYPES': ('Bearer',),
	'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
	'USER_ID_FIELD': 'username',
	'USER_ID_CLAIM': 'username',
	'JTI_CLAIM': 'jti',
	'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
	"TOKEN_OBTAIN_SERIALIZER": "core_service.serializers.CustomTokenObtainPairSerializer",
}

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.middleware.gzip.GZipMiddleware',  # Compress responses
	'core_service.middleware.PerformanceMonitoringMiddleware',  # Performance tracking
	'core_service.middleware.RequestOptimizationMiddleware',  # Request optimization
	'django.contrib.sessions.middleware.SessionMiddleware',
	'corsheaders.middleware.CorsMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'core_service.middleware.APIResponseOptimizationMiddleware',  # API optimization
] + (['core_service.middleware.DatabaseQueryOptimizationMiddleware'] if DEBUG else [])  # Query optimization in debug only

ROOT_URLCONF = 'vimp.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				'vimp.context_processors.env_variables',
			],
		},
	},
]

WSGI_APPLICATION = 'vimp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': os.getenv('DB_ENGINE'),
		'NAME': os.getenv('DB_NAME'),
		'USER': os.getenv('DB_USER'),
		'PASSWORD': os.getenv('DB_PASSWORD'),
		'HOST': os.getenv('DB_HOST'),
		'PORT': os.getenv('DB_PORT'),
		'OPTIONS': {
			'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
			'charset': 'utf8mb4',
		},
		'CONN_MAX_AGE': 600,  # 10 minutes connection reuse
		'CONN_HEALTH_CHECKS': True,  # Validate connections before use
	},
	# postgres cache
	# 'postgres': {
	# 	'ENGINE': 'django.db.backends.postgresql',
	# 	'NAME': os.getenv('PG_DB_NAME', 'django-cache'),
	# 	'USER': os.getenv('PG_DB_USER', 'postgres'),
	# 	'PASSWORD': os.getenv('PG_DB_PASSWORD', 'postgres'),
	# 	'HOST': os.getenv('PG_DB_HOST', 'localhost'),
	# 	'PORT': os.getenv('PG_DB_PORT', '5432'),
	# }
}

# Redis Cache Configuration
CACHES = {
	'default': {
		'BACKEND': 'django_redis.cache.RedisCache',
		'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379'),
		'OPTIONS': {
			'CLIENT_CLASS': 'django_redis.client.DefaultClient',
			'CONNECTION_POOL_KWARGS': {
				'max_connections': 50,
				'retry_on_timeout': True,
				'socket_keepalive': True,
				'socket_keepalive_options': {},
				'health_check_interval': 30,
			},
			'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
			'SERIALIZER': 'django_redis.serializers.pickle.PickleSerializer',
		},
		'TIMEOUT': 300,
		'KEY_PREFIX': 'vimp_prod',
		'VERSION': 1,
	},
	# "memcached": {
	# 	"BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",
	# 	"LOCATION": "127.0.0.1:11211",
	# }
}

# Session and Cache Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# Cachalot Configuration for ORM query caching
CACHALOT_ENABLED = True
CACHALOT_TIMEOUT = 600  # 10 minutes default timeout
CACHALOT_CACHE = 'default'
CACHALOT_DATABASES = ['default']
CACHALOT_UNCACHABLE_APPS = ['invoice_service', 'approval_service']

CELERY_BROKER_URL = "memory://localhost"

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'

MEDIA_ROOT = os.path.join(BASE_DIR, MEDIA_URL)
STATIC_ROOT = os.path.join(BASE_DIR, STATIC_URL)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
