# Generated by Django 4.2.26 on 2026-02-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImprestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_account', models.CharField(db_index=True, help_text='Chart of accounts G/L account number (C_Glacct)', max_length=20, unique=True, verbose_name='G/L Account Number')),
                ('description', models.CharField(help_text='G/L Account description (T_Description)', max_length=255, verbose_name='Description')),
                ('account_type', models.CharField(choices=[('COSEXP', 'Cost/Expense Account'), ('CASH', 'Cash/Bank Account'), ('OTHER', 'Other Account Type')], db_index=True, help_text='G/L Account type code (C_GlacctTc)', max_length=20, verbose_name='Account Type')),
                ('chart_of_accounts', models.CharField(default='FCOA', help_text='Chart of accounts identifier (C_Chofacct)', max_length=10, verbose_name='Chart of Accounts')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this account is active for use', verbose_name='Active Status')),
                ('last_synced', models.DateTimeField(auto_now=True, help_text='Timestamp of last sync from SAP ByD', verbose_name='Last Synced')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Imprest Item',
                'verbose_name_plural': 'Imprest Items',
                'db_table': 'imprest_items',
                'ordering': ['gl_account'],
                'indexes': [models.Index(fields=['gl_account'], name='imprest_ite_gl_acco_a9020f_idx'), models.Index(fields=['account_type'], name='imprest_ite_account_aa879d_idx'), models.Index(fields=['is_active'], name='imprest_ite_is_acti_fcdce6_idx')],
            },
        ),
    ]
