# Generated by Django 4.2 on 2024-04-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_settings',
            field=models.JSONField(default=dict),
        ),
    ]
