# Generated by Django 4.2 on 2024-03-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_service', '0002_alter_vendorprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='id_type',
            field=models.CharField(choices=[('phone', 'PHONE'), ('email', 'EMAIL')], max_length=7),
        ),
    ]
