# Generated by Django 4.2 on 2024-03-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_service', '0003_alter_tempuser_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='id_type',
            field=models.CharField(choices=[('email', 'EMAIL'), ('phone', 'PHONE')], max_length=7),
        ),
    ]
