# Generated by Django 4.2 on 2025-02-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_service', '0003_customuser_secret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '4.1 User', 'verbose_name_plural': '4.1 Users'},
        ),
        migrations.AlterModelOptions(
            name='tempuser',
            options={'verbose_name': '4.3 Temp User', 'verbose_name_plural': '4.3 Temp Users'},
        ),
        migrations.AlterModelOptions(
            name='vendorprofile',
            options={'verbose_name': '4.2 Vendor Profile', 'verbose_name_plural': '4.2 Vendor Profiles'},
        ),
    ]
