# Generated by Django 4.2 on 2024-04-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_service', '0003_alter_vendorprofile_vendor_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='id_type',
            field=models.CharField(choices=[('phone', 'PHONE'), ('email', 'EMAIL')], max_length=7),
        ),
    ]
