# Generated by Django 4.2 on 2024-04-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_service', '0004_alter_tempuser_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='id_type',
            field=models.CharField(choices=[('phone', 'PHONE'), ('email', 'EMAIL')], max_length=7),
        ),
    ]
