# Generated by Django 4.2 on 2024-12-19 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=10, unique=True)),
                ('account_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GLEntryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50)),
                ('state_description', models.CharField(max_length=255)),
                ('transaction_value_field', models.CharField(max_length=32)),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_settings.glaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryGLEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_id', models.CharField(max_length=10, unique=True)),
                ('product_category_description', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('receipt', 'Receipt'), ('invoice', 'Invoice')], max_length=10)),
                ('credit_states', models.ManyToManyField(related_name='receipt_credit_states', to='app_settings.glentrystate')),
                ('debit_states', models.ManyToManyField(related_name='receipt_debit_states', to='app_settings.glentrystate')),
            ],
        ),
    ]
