# Generated by Django 4.2 on 2024-12-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategoryglentry',
            name='action',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('invoice_approval', 'Invoice Approval')], max_length=20),
        ),
    ]
