# Generated by Django 4.2 on 2024-12-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_alter_productcategoryglentry_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategoryglentry',
            name='product_category_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='productcategoryglentry',
            constraint=models.UniqueConstraint(fields=('product_category_id', 'action'), name='unique_product_category_action'),
        ),
    ]
