# Generated by Django 4.2 on 2025-02-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0021_alter_conversion_options_and_more'),
        ('app_settings', '0003_alter_productcategoryglentry_product_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionProxy',
            fields=[
            ],
            options={
                'verbose_name': '1.2.2 Products - Conversion',
                'verbose_name_plural': '1.2.2 Products - Conversions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('egrn_service.conversion',),
        ),
        migrations.CreateModel(
            name='ProductConfigurationProxy',
            fields=[
            ],
            options={
                'verbose_name': '1.2.1 Products - Configuration',
                'verbose_name_plural': '1.2.1 Products - Configurations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('egrn_service.productconfiguration',),
        ),
        migrations.CreateModel(
            name='StoreProxy',
            fields=[
            ],
            options={
                'verbose_name': '1.1 Store',
                'verbose_name_plural': '1.1 Stores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('egrn_service.store',),
        ),
        migrations.CreateModel(
            name='SurchargeProxy',
            fields=[
            ],
            options={
                'verbose_name': '1.4 Surcharge',
                'verbose_name_plural': '1.4 Surcharges',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('egrn_service.surcharge',),
        ),
        migrations.AlterModelOptions(
            name='glaccount',
            options={'verbose_name_plural': '1.3.1 Ledger - Accounts'},
        ),
        migrations.AlterModelOptions(
            name='glentrystate',
            options={'verbose_name_plural': '1.3.3 Ledger - States'},
        ),
        migrations.AlterModelOptions(
            name='productcategoryglentry',
            options={'verbose_name_plural': '1.3.2 Ledger - Entries for Product Categories'},
        ),
    ]
