# Generated by Django 4.2 on 2025-02-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byd_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bydpostingstatus',
            options={'verbose_name_plural': '6.1 Posting Reports'},
        ),
    ]
