# Generated by Django 4.2 on 2025-02-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byd_service', '0002_alter_bydpostingstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bydpostingstatus',
            name='django_q_task_name',
            field=models.CharField(default='vimp.tasks.create_grn_on_byd', max_length=255),
        ),
    ]
