# Generated by Django 4.2 on 2024-03-13 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_service', '0003_alter_tempuser_id_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=32, unique=True)),
                ('po_id', models.IntegerField(unique=True)),
                ('total_net_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('total_gross_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('date', models.DateField()),
                ('metadata', models.JSONField(default=dict)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_service.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('icg_warehouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('icg_warehouse_code', models.CharField(max_length=20, unique=True)),
                ('byd_cost_center_code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=32, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('metadata', models.JSONField(default=dict)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='egrn_service.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.IntegerField(unique=True)),
                ('received_date', models.DateField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egrn_service.purchaseorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egrn_service.store')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceivedLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egrn_service.goodsreceivednote')),
                ('purchase_order_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egrn_service.purchaseorderlineitem')),
            ],
        ),
    ]
