# Generated by Django 4.2 on 2024-04-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=32, unique=True)),
                ('required_fields', models.JSONField(default=dict)),
                ('conversion_factor', models.JSONField(default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
