# Generated by Django 4.2 on 2024-03-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivedlineitem',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
    ]
