# Generated by Django 4.2 on 2024-06-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('conversion_field', models.JSONField(default=dict)),
                ('conversion_method', models.CharField(choices=[('chicken_conversion', 'chicken_conversion')], max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=32, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_conversion', to='egrn_service.conversion')),
            ],
        ),
    ]
