# Generated by Django 4.2 on 2024-05-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0002_productconversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReceiptFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=32, unique=True)),
                ('extra_fields', models.JSONField(default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
