# Generated by Django 4.2 on 2024-06-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0003_goodsreceivedlineitem_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivedlineitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
