# Generated by Django 4.2 on 2024-03-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0003_alter_goodsreceivedlineitem_purchase_order_line_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivedlineitem',
            name='purchase_order_line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egrn_service.purchaseorderlineitem'),
        ),
    ]
