# Generated by Django 4.2 on 2024-05-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0003_productreceiptfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
