# Generated by Django 4.2 on 2024-05-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0004_purchaseorderlineitem_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivedlineitem',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='extra_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
