# Generated by Django 4.2 on 2024-06-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0004_alter_goodsreceivedlineitem_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='product_code',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
