# Generated by Django 4.2 on 2024-04-12 00:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0004_alter_goodsreceivedlineitem_purchase_order_line_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='received_date',
        ),
        migrations.AddField(
            model_name='goodsreceivedlineitem',
            name='date_received',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodsreceivedlineitem',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='egrn_service.goodsreceivednote'),
        ),
        migrations.AlterField(
            model_name='goodsreceivedlineitem',
            name='purchase_order_line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_line_item', to='egrn_service.purchaseorderlineitem'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='egrn_service.purchaseorder'),
        ),
    ]
