# Generated by Django 4.2 on 2024-06-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_service', '0002_alter_invoice_options_and_more'),
        ('egrn_service', '0005_purchaseorderlineitem_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderlineitem',
            old_name='product_code',
            new_name='product_id',
        ),
        migrations.CreateModel(
            name='ProductSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=32)),
                ('surcharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_surcharge', to='invoice_service.surcharge')),
            ],
            options={
                'unique_together': {('product_id', 'surcharge')},
            },
        ),
    ]
