# Generated by Django 4.2 on 2024-04-12 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0005_remove_goodsreceivednote_received_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_gross_amount',
        ),
    ]
