# Generated by Django 4.2 on 2024-04-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0006_remove_purchaseorder_total_gross_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='unit_of_measurement',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
    ]
