# Generated by Django 4.2 on 2024-06-25 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0007_delete_productsurcharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('type', models.CharField(default='Value Added Tax', max_length=50, verbose_name='Type')),
                ('rate', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Rate')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=32)),
                ('surcharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_surcharge', to='egrn_service.surcharge')),
            ],
            options={
                'unique_together': {('product_id', 'surcharge')},
            },
        ),
    ]
