# Generated by Django 4.2 on 2024-06-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0009_purchaseorderlineitem_tax_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surcharge',
            name='rate',
            field=models.FloatField(verbose_name='Rate'),
        ),
    ]
