# Generated by Django 4.2 on 2024-07-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0010_alter_surcharge_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivedlineitem',
            name='gross_value_received',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsreceivedlineitem',
            name='net_value_received',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
            preserve_default=False,
        ),
    ]
