# Generated by Django 4.2 on 2024-07-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0011_goodsreceivedlineitem_gross_value_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='conversion_method',
            field=models.CharField(choices=[('chicken_conversion', 'chicken_conversion'), ('nbc_products_volume_conversion', 'nbc_products_volume_conversion')], max_length=100),
        ),
    ]
