# Generated by Django 4.2 on 2024-08-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0012_alter_conversion_conversion_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='delivery_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to='egrn_service.store'),
        ),
    ]
