# Generated by Django 4.2 on 2024-08-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0013_purchaseorderlineitem_delivery_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
