# Generated by Django 4.2 on 2024-08-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0014_store_metadata_store_store_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='posted_to_icg',
            field=models.BooleanField(default=False),
        ),
    ]
