# Generated by Django 4.2 on 2024-09-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0015_goodsreceivednote_posted_to_icg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=32, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_conversion', to='egrn_service.conversion')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductConversion',
        ),
    ]
