# Generated by Django 4.2 on 2024-09-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0016_productconfiguration_delete_productconversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productconfiguration',
            name='conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_conversion', to='egrn_service.conversion'),
        ),
    ]
