# Generated by Django 4.2 on 2024-11-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0017_alter_productconfiguration_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='conversion_method',
            field=models.CharField(choices=[('chicken_conversion', 'chicken_conversion'), ('cut9_conversion', 'cut9_conversion'), ('nbc_products_volume_conversion', 'nbc_products_volume_conversion')], max_length=100),
        ),
    ]
