# Generated by Django 4.2 on 2024-12-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0019_remove_goodsreceivednote_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='posted_to_icg',
        ),
        migrations.AddField(
            model_name='goodsreceivedlineitem',
            name='posted_to_icg',
            field=models.BooleanField(default=False),
        ),
    ]
