# Generated by Django 4.2 on 2025-11-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0021_alter_conversion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockConsumptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=32)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=32, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=64, null=True)),
                ('external_item_id', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('date_consumed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stock Consumption Record',
                'verbose_name_plural': 'Stock Consumption Records',
                'ordering': ['-date_consumed'],
            },
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='inbound_delivery_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='inbound_delivery_notification_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='inbound_delivery_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='is_nullified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='nullified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='nullified_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
