# Generated by Django 4.2 on 2026-02-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0022_stockconsumptionrecord_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockconsumptionrecord',
            options={'ordering': ['-date_consumed'], 'verbose_name': '2.5 Stock Consumption Record', 'verbose_name_plural': '2.5 Stock Consumption Records'},
        ),
    ]
