# Generated by Django 4.2 on 2024-04-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egrn_service', '0007_purchaseorderlineitem_unit_of_measurement'),
        ('core_service', '0005_alter_tempuser_id_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_document_id', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('payment_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approval_metadata', models.JSONField(default=dict)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='egrn_service.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core_service.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Surcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=5, verbose_name='Code')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('type', models.CharField(default='Value Added Tax', max_length=50, verbose_name='Type')),
                ('rate', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Rate')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('discountable', models.BooleanField(default=False)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed'), ('none', 'None')], default='none', max_length=10, verbose_name='Discount Type')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Discount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoive_line_items', to='invoice_service.invoice')),
                ('po_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egrn_service.purchaseorderlineitem')),
                ('surcharges', models.ManyToManyField(to='invoice_service.surcharge')),
            ],
        ),
    ]
