# Generated by Django 4.2 on 2024-05-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': [('can_sign_signable', 'Can sign a signable object.')]},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='approval_metadata',
            new_name='signatories',
        ),
        migrations.AddField(
            model_name='invoice',
            name='digest',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
