# Generated by Django 4.2 on 2024-06-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0008_surcharge_productsurcharge'),
        ('invoice_service', '0003_productsurcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='surcharges',
            field=models.ManyToManyField(to='egrn_service.surcharge'),
        ),
        migrations.DeleteModel(
            name='ProductSurcharge',
        ),
        migrations.DeleteModel(
            name='Surcharge',
        ),
    ]
