# Generated by Django 4.2 on 2024-07-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_service', '0005_alter_invoice_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='discountable',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='discounted_gross_total',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='surcharges',
        ),
    ]
