# Generated by Django 4.2 on 2024-07-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_service', '0006_remove_invoicelineitem_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='surcharge_amount',
            new_name='tax_amount',
        ),
    ]
