# Generated by Django 4.2 on 2024-07-17 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0012_alter_conversion_conversion_method'),
        ('invoice_service', '0007_rename_surcharge_amount_invoicelineitem_tax_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='invoice',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='egrn_service.goodsreceivednote'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='grn_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='egrn_service.goodsreceivedlineitem'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='egrn_service.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='po_line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egrn_service.purchaseorderlineitem'),
        ),
    ]
