# Generated by Django 4.2 on 2024-07-17 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_service', '0012_alter_conversion_conversion_method'),
        ('invoice_service', '0008_remove_invoicelineitem_quantity_invoice_grn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grn', to='egrn_service.goodsreceivednote'),
        ),
    ]
