# Generated by Django 4.2 on 2024-08-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_service', '0009_invoicelineitem_quantity_alter_invoice_grn'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='current_pending_signatory',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
