# Generated by Django 4.2 on 2024-09-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_service', '0010_invoice_current_pending_signatory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': [('accounts_payable', 'The accounts payable role.'), ('line_manager', 'The line manager role.'), ('internal_control', 'The internal control role.'), ('head_of_finance', 'The head of finance role.'), ('snr_manager_finance', 'The snr manager  of finance role.'), ('dmd_ss', 'The DMD SS role.'), ('md', 'The managing director role.')]},
        ),
    ]
