# Generated by Django 4.2 on 2025-02-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_service', '0011_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': '3.1 Invoice', 'verbose_name_plural': '3.1 Invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'verbose_name': '3.2 Invoice Line Item', 'verbose_name_plural': '3.2 Invoice Line Items'},
        ),
    ]
